// Generated by scripts/generate-browsers.mjs — do not edit
// Generated at: 2025-10-30T19:15:46.491Z
export const GENERATED_BROWSERS = [
  "and_chr 141",
  "and_ff 143",
  "and_qq 14.9",
  "and_uc 15.5",
  "android 141",
  "chrome 141",
  "chrome 140",
  "chrome 139",
  "chrome 138",
  "chrome 134",
  "chrome 126",
  "chrome 112",
  "chrome 109",
  "edge 141",
  "edge 140",
  "edge 139",
  "firefox 144",
  "firefox 143",
  "firefox 142",
  "ios_saf 26.0",
  "ios_saf 18.5-18.6",
  "kaios 3.0-3.1",
  "kaios 2.5",
  "op_mini all",
  "op_mob 80",
  "opera 122",
  "opera 121",
  "safari 26.0",
  "safari 18.5-18.6",
  "samsung 28",
  "samsung 27"
] as string[];

export const MIN_VERSIONS: Record<string, number> = {
  "and_chr": 141,
  "and_ff": 143,
  "and_qq": 14,
  "and_uc": 15,
  "android": 141,
  "chrome": 109,
  "edge": 139,
  "firefox": 142,
  "ios_saf": 18,
  "kaios": 2,
  "op_mob": 80,
  "opera": 121,
  "safari": 18,
  "samsung": 27
} as Record<string, number>;

export default GENERATED_BROWSERS;
